# Generated by Django 4.1.5 on 2023-02-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('title', 'category')},
        ),
    ]
