# Generated by Django 4.1.5 on 2023-04-22 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu_item', '0002_alter_menuitem_unique_together'),
        ('cart', '0002_alter_cart_unique_together_cart_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_item.menuitem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'menu_item')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
