# Generated by Django 4.1.5 on 2023-04-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_item', '0002_alter_menuitem_unique_together'),
        ('cart', '0003_cart_menu_item_cart_price_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_item.menuitem'),
        ),
    ]
